spring.datasource.name=CRUD-Operations
# JWT Secret Key
app.jwt.secret=mySuperSecretJwtKeyForSpringBootApplication12345

# Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/crud_db
spring.datasource.username=postgres
spring.datasource.password=root

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# PostgreSQL SQL Dialect
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect